# Generated by Django 4.2.4 on 2023-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
