# Generated by Django 4.2.4 on 2023-08-24 01:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_delivery_prospect_delivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delivery_prospect',
            new_name='DeliveryProspect',
        ),
    ]
